# Use Maven with OpenJDK
FROM maven:3.8.5-openjdk-17

# Install Docker CLI inside this image
USER root
RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean

# Set working directory
WORKDIR /app

# Default command (can be overridden by Jenkins)
CMD ["bash"]
